var riceProducts = [
    {
        id: "first",
        idn: "1",
        image: "../images/rice-products-pics/aishwarya.jpg",
        title: "Aishwarya Wada Kolam Organic Rice",
        pSize: "10-50 Kg",
        brand: "Aishwarya",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        id: "second",
        idn: "2",
        image: "../images/rice-products-pics/panchshil.jpg",
        title: "Panchshil Old Wada Kolam",
        pSize: "50 kg",
        brand: "Panchshil",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 5800/Ton"
    },
    {
        id: "third",
        idn: "3",
        image: "../images/rice-products-pics/kolam.jpg",
        title: "Kolam Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "4",
        image: "../images/rice-products-pics/steam.jpg",
        title: "Steam Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "5",
        image: "../images/rice-products-pics/steam-jeera.jpg",
        title: "Steam Jira Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "6",
        image: "../images/rice-products-pics/jeeraLachkari.jpg",
        title: "Jeera Rice LACHKARI",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "7",
        image: "../images/rice-products-pics/kolam-tukda.jpg",
        title: "Kolam Tukda Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "8",
        image: "../images/rice-products-pics/pulav.jpg",
        title: "Fresh Organic Pulav Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "9",
        image: "../images/rice-products-pics/biryani.jpg",
        title: "Biryani Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "10",
        image: "../images/rice-products-pics/old-HMT.jpg",
        title: "Old HMT Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "11",
        image: "../images/rice-products-pics/super-mogra.jpg",
        title: "Super Mogra Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "100% Pure",
        organic: "Organic and Soft",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "12",
        image: "../images/rice-products-pics/hmt-raw.jpg",
        title: "HMT Raw Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "13",
        image: "../images/rice-products-pics/basmati-tibar.jpg",
        title: "Basmati Tibar Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "14",
        image: "../images/rice-products-pics/basmati-tukda.jpg",
        title: "Basmati Tukda Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "15",
        image: "../images/rice-products-pics/basmati-biryani.jpg",
        title: "Basmati Biryani Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "16",
        image: "../images/rice-products-pics/surti-kolam-broken.jpg",
        title: "Surti Kolam Broken Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "17",
        image: "../images/rice-products-pics/surti-wada.jpg",
        title: "Surti Wada Old Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "18",
        image: "../images/rice-products-pics/surti-lachkari.jpg",
        title: "Surti Lachkari Rice",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    },
    {
        idn: "19",
        image: "../images/rice-products-pics/basmati1121.jpg",
        title: "Basmati 1121",
        pSize: "10-50 Kg",
        brand: "-",
        shelfLife: "12 Months",
        quality: "A Grade",
        organic: "Organic",
        pType: "Jute Bag",
        price: "Rs 24-90/Kilogram"
    }
];

module.exports = riceProducts;